// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPbdtE5YdopfQ0e5Cu7hZiS6N1bgFCDM',
    appId: '1:589947265898:web:db8b5c8f07c9cb9bb57b13',
    messagingSenderId: '589947265898',
    projectId: 'fir-authentication-3c552',
    authDomain: 'fir-authentication-3c552.firebaseapp.com',
    storageBucket: 'fir-authentication-3c552.appspot.com',
    measurementId: 'G-X4S3Y4MLF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb-YjRSs3R4TZ7gsIss7TUYM9vsWCd4Kw',
    appId: '1:589947265898:android:4c170609a6e432f5b57b13',
    messagingSenderId: '589947265898',
    projectId: 'fir-authentication-3c552',
    storageBucket: 'fir-authentication-3c552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqpssmvNw3V-U-IxsVuLLwibja99zxlHI',
    appId: '1:589947265898:ios:480a71a7e52c0243b57b13',
    messagingSenderId: '589947265898',
    projectId: 'fir-authentication-3c552',
    storageBucket: 'fir-authentication-3c552.appspot.com',
    iosClientId: '589947265898-6o0as0ikrkjuu39lq0m4tmdk4c2il5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqpssmvNw3V-U-IxsVuLLwibja99zxlHI',
    appId: '1:589947265898:ios:480a71a7e52c0243b57b13',
    messagingSenderId: '589947265898',
    projectId: 'fir-authentication-3c552',
    storageBucket: 'fir-authentication-3c552.appspot.com',
    iosClientId: '589947265898-6o0as0ikrkjuu39lq0m4tmdk4c2il5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
